name: Test

on:
  push:
    branches: [ master, lint ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.7', '3.8', '3.9']
        env:
          - DJANGO_VERSION=1.11.29
          - DJANGO_VERSION=2.2.28
          - DJANGO_VERSION=3.2.19
          - DJANGO_VERSION=4.2.1
          - FLASK_VERSION=1.0.4
          - FLASK_VERSION=1.1.1
        exclude:
          - python-version: '3.7'
            env: DJANGO_VERSION=4.2.1

    steps:

    - name: Check out ${{ github.ref }}
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        export ${{ matrix.env }}
        python -m pip install --upgrade pip
        pip install psutil six mock itsdangerous nose testfixtures blinker wheel
        ./scripts/install_frameworks.sh
        python setup.py develop

    - name: Run Tests
      run: |
        export ${{ matrix.env }}
        python setup.py test
